id = "tokyonight-icons"
name = "Tokyo Night Icons"
version = "0.0.1"
schema_version = 1
authors = [""]
description = "Icons for Zed based on Lucide Icons with a Tokyo Night theme"
repository = "https://github.com/kjvdven/zed-tokyonight-icons"
